fix sshkey parameter type
sshkey module convert_sshkey method expects a list of keys

fixes:
pb@foo:~/git$ gandi paas update --sshkey kalou tests
Usage: gandi paas update [OPTIONS] RESOURCE

Error: unknown identifier k