disk: fix default value when creating a disk
Since we introduced a SizeParamType, default value should be a string

This fixes the following TB:
TypeError: 'int' object is not iterable

Signed-off-by: William Dauchy <william@gandi.net>